site_name: y_arena_odor_controller
site_description: This board controls the y-arena odors for the Janelia Turner lab
site_author: Peter Polidoro

copyright: 'Copyright &copy; 2020 Peter Polidoro'

theme:
  name: 'material'
  language: en
  logo: 'img/y_logo.png'
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: Deep Purple
  font:
    text: Ubuntu
    code: Roboto Mono

repo_name: 'y_arena_odor_controller'
repo_url: 'https://github.com/janelia-kicad/y_arena_odor_controller.git'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true

nav:
    - Home: index.md
    - Schematic:
       - schematic00: schematic/schematic00.md
       - schematic01: schematic/schematic01.md
       - schematic02: schematic/schematic02.md
       - schematic03: schematic/schematic03.md
       - schematic04: schematic/schematic04.md
       - schematic05: schematic/schematic05.md
       - schematic06: schematic/schematic06.md
       - schematic07: schematic/schematic07.md
       - schematic08: schematic/schematic08.md
       - schematic09: schematic/schematic09.md
    - Gerbers:
       - gerbers00: gerbers/gerbers00.md
       - gerbers01: gerbers/gerbers01.md
    - Bill of Materials:
       - PCB Parts: bom/pcb.md
       - Supplemental Parts: bom/supplemental.md
